### ISSUE TITLE
Conversion from ORCA025 to ORCA X?

### ISSUE THREAD

**Issue by ranguli** [brodeau/sosie#11]
Hi there. I did some digging in the docs, and I couldn't figure out whether or not SOSIE supports ORCA025 conversion into a .nc file in the ORCA1 or ORCA2 format? It's not my area of expertise but I need to convert it for someone else. 

Thanks!

**Comment by ds4g15** [comment]
Hi - did you ever figure this out?
Thanks in advance!

**Comment by ranguli** [comment]
@ds4g15 - I don't believe I ever got it working, sorry!
