### ISSUE TITLE
Interpolation between A-Grid and C-Grid

### ISSUE THREAD

**Issue by SOFIADAL** [brodeau/sosie#18]
Hello,

I wanted to ask whether sosie is able to interpolated from C-grid to A-grid data. I have vertical velocities w in a native NEMO C-grid and I am planning to use an A-grid file to interpolate the vertical velocities in A grid as well.

Will that work? How will I know if my file is interpolated in the A-grid.
Thank you very much for your answer.
Kind regards,
Sofi

**Comment by raphaeldussin** [comment]
you should look at [xgcm](https://xgcm.readthedocs.io/en/latest/), it looks more appropriate for your problem.
