### ISSUE TITLE
Issue with Sosie interpolation

### ISSUE THREAD

**Issue by sofiadarm** [brodeau/sosie#2]
Dear sirs,

Good afternoon. My name is Sofia and I am a student currently using sosie.x for interpolation in NEMOMED8 (drown method). I recently encountered a problem, during which I could not seem to apply the sosie interpolation to another model file (Not NEMO), because the output was not interpolated properly for some reason. Perhaps the grid of the model (curvilinear) file has a particuliarity that sosie does not recognise (?). Could you please give me your insights on that?

I am attaching here a .docx file called "sosie.out" where it shows where exactly is the error encountered during the .map creation file and I am also attaching images taken with ncview of the original .nc file I wanted to interpolate and its variables. (lon,lat,sst). It is showing the Mediterranean region only that the grid is tilted or rotated somehow. (It is the Mediterranean Sea region I am interested in)

Finally I am attaching a file with two images (from ncview), to show you exactly what is the difference between the original file and the interpolated. In this file the interpolated plot is named : sst_tr04_nas-583_dm.nc and the original file is the plot named : tr04_nas_583_dm_2005.nc.

I hope this information will be helpful. Thank you in advance for your time and help,
Kind regards,
Sofia Darmaraki

![sst_variable_of_original_file](https://user-images.githubusercontent.com/29405288/27088105-19dfcbbe-5057-11e7-9231-22586effb91e.png)
![longitude_of_original_file](https://user-images.githubusercontent.com/29405288/27088111-1ddc5c28-5057-11e7-9131-60bf302d089a.png)
![latitude_of_original_file](https://user-images.githubusercontent.com/29405288/27088120-21b71522-5057-11e7-97db-f15dc4f61066.png)
![grid_details_of_original_file](https://user-images.githubusercontent.com/29405288/27088126-271ccbce-5057-11e7-9b0b-56c028c567e8.png)
![interpolated_vs_original_file](https://user-images.githubusercontent.com/29405288/27088647-873483b6-5058-11e7-92bf-d50e8500e8af.png)
[sosie_out.docx](https://github.com/brodeau/sosie/files/1071777/sosie_out.docx)

**Comment by brodeau** [comment]
Hello Sofia,
Please provide us with a download link to a tarball containing everything we need to test your setup, namely:
- your namelist
- and all the netcdf files mentioned in you namelist
So that we just have to unpack the tarball and directly test it!

Cheers, /laurent

**Comment by sofiadarm** [comment]
Dear sirs,

Thank you very much for your immediate answer. Can you please provide me with an email adresse to send it because the file size is too big to send even with zip from this post?

Thank you again for your help and time,
Kind regards,
Sofia Darmaraki

**Comment by sofiadarm** [comment]
Dear sirs,

Good afternoon. It is Sofia Darmaki . Thank you for your immediate answer.
I am sending you here the files you requested because my work email does
not allow me to transfer big-size files.

​
 tarball_sofia_darmaraki.tar.gz
<https://drive.google.com/file/d/0B8SfhOH-n1s8NGtISDVxbFhYdFk/view?usp=drive_web>
​ Kind regards,
Sofia Darmaraki

**Comment by sofiadarm** [comment]
I tries already to send the files through my personal email (sofia.darm@gmail.com) because my work email does not allow me to transfer big-size files.

Please let me know if you received any such emails,

Kind regards,
Sofia Darmaraki

**Comment by brodeau** [comment]
your namelist says
"cf_in     = 'input.nc'"

I don't have "input.nc" in your tarball!

**Comment by sofiadarm** [comment]
Dear Laurent,

Good morning and thank for the help. 

The input.nc is just the file you want to interpolate, because this section of the namelist script refers to the characteristics of the file you want to interpolate. We just name it like this so we will not have to type every time the file of each file we want to interpolate. I am copy pasting here an example of the script we use to run the namelist :

#!/bin/sh

dirin=/run/media/darmarakis/WD_CNRM/DATA_MED_CORDEX/UAH_UNIV_DATA/NAS_1950_2005
dirout=/run/media/darmarakis/WD_CNRM/DATA_MED_CORDEX/UAH_UNIV_DATA/NAS_1950_2005/INTERPOLATED_FILES

/bin/rm namelist
ln -s namelist_HIST_NAS_1950_2005 namelist
/bin/rm input.nc
ficin=$dirin/tr04_nas_583_dm_2004.nc
ln -s $ficin input.nc
./sosie.x
 mv sst_tr04_nas-583_dm.nc $dirout/interpolated_sst_tr04_nas-583_dm_${an}.nc
rm -f sst_tr04_nas-583_dm.nc
let an= $an + 1
  done

**Comment by brodeau** [comment]
Well, so the field you want to interpolate is "sst" found in "tr04_nas_583_dm_2004.nc" right?
So it works fine for me.
1/ update to the up-to-date version of SOSIE ! From you namelist I see you use a pretty old one...
2/ mind that your source grid is not regular so that it is impossible to use the Akima method, so you have to use the bilinear method.

Attached is a slightly updated namelist that works fine to do what you want to do (I tested it with your example), but again you need an up-to-date sosie.
Also, it will take a few minutes to build the file that contains the remapping weights "sosie_mapping_tr04_nas-583.nc", but this only needs to be done once, so conserve this file.

[namelist_HIST_NAS_1950_2005.txt](https://github.com/brodeau/sosie/files/1073946/namelist_HIST_NAS_1950_2005.txt)

Cheers, /laurent

**Comment by sofiadarm** [comment]
Thanks a lot for that,

1: How do I get the updated version of sosie?
2: How do I change to the bilinear interpolation instead of akima?
2: So you did not get any warnings during the creation of the map files?Like the one I got  (you can see it on the sosie_out.docx I sent you yesterday), a warning that says that "there are some problematic areas, relax it might be outside of your domain"???
3. Does the field of the interpolated file looks like the field of the original file then?

**Comment by sofiadarm** [comment]
Ok I saw where the bilinear method is changed. Thanks!

**Comment by brodeau** [comment]
1. update the code and recompile it.
  To update the code:
 "git pull" if you are using git 
 "svn update" if you are using svn
 then make!

If you have no idea what I'm talking about just contact your sys admin and tell him to do this!

The namelist I sent you has the correct setup!

/laurent

**Comment by sofiadarm** [comment]
OK So I will contact my administrator cause...i do not have any idea how to do this. 
Thanks a lot for this help. I will be back with news how it worked for me!

Sofi

**Comment by sofiadarm** [comment]
I spoke with my administrator for updating the SOsie version. In the meantime is it possible to send me a pipcture of the interpolated file please?

Thank you again for your help,
Regards,
Sofi

**Comment by sofiadarm** [comment]
Dear Laurent,

It seems that the updated version works perfectly!!!!Thank you  immensely!!!!You saved my day!!!!

Kind regards,
Sofia

**Comment by sofiadarm** [comment]
Hello again Laurent,

We all here in the lab would like to thank you again for your help and I transferring a question someone had. 
What is the mask_drown_field.x? They said that it is compiled at the same time as sosie.x but is not mentioned at the README documentation.

Regards,
Sofia

**Comment by brodeau** [comment]
Glad to hear I saved your day!
mask_drown_field.x field is an executable to propagate/extrapolate sea values (defined where mask==1) of a given field onto continents (defined where mask==0) to avoid problems, like when doing contour plots...
To avoid the same kind of problems when interpolating (continental values that pollute sea values during interpolation) always set the namelist 'ldrown' to true when using sosie.x 

There is a test case example, just run the script "test_drown.sh" in the "examples" directory and you will understand...

A+ /laurent

**Comment by sofiadarm** [comment]
Ok thanks for the info. I will pass it to the people here. And just one last question.

I have interpolated more data (coming from different models and thus grids) with the previous version of SOSIE without any problem. Do you think I should re-interpolated everything now with the new version so as to have a "clean" interpolation method for everything, or it does not matter?

Sofi

**Comment by brodeau** [comment]
No it doesn't matter. You can keep you old interpolated fields.
There was no bugs affecting the quality of the interpolation in previous versions! Just more chances to run into errors when interpolating...

Cheers, /laurent

**Comment by sofiadarm** [comment]
Thanks a lot for that!

Have a nice day!
Sofi

**Comment by sofiadarm** [comment]
Dear Laurent,

Good morning. I am also sending you here another tarball with another model
file (sst2005_2D.nc) which I encountered a problem during interpolation. (I
think it is because the other model's land surface is greater than ours). I
used the new version of sosie and namelist and I am also attaching a
picture of the final interpolation. Could you perhaps help me with that?

Thanks in advance for your time,
Kind regards,
Sofia​
 tarball_sofia_darmaraki.zip
<https://drive.google.com/file/d/0B8SfhOH-n1s8OE83ZGI2dllJWHM/view?usp=drive_web>
​

2017-06-13 17:48 GMT+02:00 Sofia Darmar <sofia.darm@gmail.com>:

> Dear sirs,
>
> Good afternoon. It is Sofia Darmaki . Thank you for your immediate answer.
> I am sending you here the files you requested because my work email does
> not allow me to transfer big-size files.
>
> ​
>  tarball_sofia_darmaraki.tar.gz
> <https://drive.google.com/file/d/0B8SfhOH-n1s8NGtISDVxbFhYdFk/view?usp=drive_web>
> ​ Kind regards,
> Sofia Darmaraki
>

**Comment by brodeau** [comment]
Please provide us with a tarball that will work out of the box. Namely with a namelist adapted with what's inside the tarball and not other things...

**Comment by brodeau** [comment]
And I see no pictures anywhere

**Comment by sofiadarm** [comment]
I am really Sorry, I do not know why it did not work before. Maybe because
i send it via my personal email. I try again here
The tarball contains:

1:lance_analysed_sst.sh -> script to run the namelist
2: namelist_HIST_CMCC.txt -> the namelist used to do the interpolation
3: med.nc -> the mask of the target grid
4: tmask_NEMO_MED8.nc ->the mask of the target grid in another format
5: sst2005_2D.nc -> the file to be interpolated
6: RCSM4-2.03_2004_2D.nc -> the file from where we take the target grid

Please let me know if you received eveything ok this time,
Thank you in advance for your time,
Kind regards,
Sofia Darmaraki​
 tarball2_sofia_darmaraki.tar
<https://drive.google.com/file/d/0B8SfhOH-n1s8dl91VXkwWW9sazA/view?usp=drive_web>
​

2017-06-13 17:48 GMT+02:00 Sofia Darmar <sofia.darm@gmail.com>:

> Dear sirs,
>
> Good afternoon. It is Sofia Darmaki . Thank you for your immediate answer.
> I am sending you here the files you requested because my work email does
> not allow me to transfer big-size files.
>
> ​
>  tarball_sofia_darmaraki.tar.gz
> <https://drive.google.com/file/d/0B8SfhOH-n1s8NGtISDVxbFhYdFk/view?usp=drive_web>
> ​ Kind regards,
> Sofia Darmaraki
>

**Comment by sofiadarm** [comment]
I am also sending the tar in a slightly different format just in case,
here:
​
 tarball2_sofia_darmaraki.tar.gz
<https://drive.google.com/file/d/0B8SfhOH-n1s8ZUhySTFzcWNLU1E/view?usp=drive_web>
​

2017-06-15 13:18 GMT+02:00 Sofia Darmar <sofia.darm@gmail.com>:

> I am really Sorry, I do not know why it did not work before. Maybe because
> i send it via my personal email. I try again here
> The tarball contains:
>
> 1:lance_analysed_sst.sh -> script to run the namelist
> 2: namelist_HIST_CMCC.txt -> the namelist used to do the interpolation
> 3: med.nc -> the mask of the target grid
> 4: tmask_NEMO_MED8.nc ->the mask of the target grid in another format
> 5: sst2005_2D.nc -> the file to be interpolated
> 6: RCSM4-2.03_2004_2D.nc -> the file from where we take the target grid
>
> Please let me know if you received eveything ok this time,
> Thank you in advance for your time,
> Kind regards,
> Sofia Darmaraki​
>  tarball2_sofia_darmaraki.tar
> <https://drive.google.com/file/d/0B8SfhOH-n1s8dl91VXkwWW9sazA/view?usp=drive_web>
> ​
>
> 2017-06-13 17:48 GMT+02:00 Sofia Darmar <sofia.darm@gmail.com>:
>
>> Dear sirs,
>>
>> Good afternoon. It is Sofia Darmaki . Thank you for your immediate
>> answer. I am sending you here the files you requested because my work email
>> does not allow me to transfer big-size files.
>>
>> ​
>>  tarball_sofia_darmaraki.tar.gz
>> <https://drive.google.com/file/d/0B8SfhOH-n1s8NGtISDVxbFhYdFk/view?usp=drive_web>
>> ​ Kind regards,
>> Sofia Darmaraki
>>
>
>

**Comment by brodeau** [comment]
Problem is that your sst field in sst2005_2D.nc is 0 on the continents and that the '_FillValue' is something else than '0.' ... So DROWN was not doing its job because continents where considered as sea with a sst of 0 instead of being considered as land!

I committed a change in sosie so it's now possible to by-pass such an issue, so get the new version of sosie compiled and in your namelist use:

```
cf_lsm_in = 'val-'
cv_lsm_in = '0.0001'
```

Also have:
`lregin    = T`
and
`cmethod  = 'akima'`
Because your source domain is actually regular...

Worked fine for me...
/laurent

```
!! cf_lsm_in : (only relevant if ldrown==.true.)
!!             file containing the input land-sea mask [char]
!!             Alternatively:
!!             * specify " cf_lsm_in = 'missing_value' " if a 'missing_value' netcdf
!!               attribute defines the mask on the input data field
!!             * specify " cf_lsm_in = 'nan' " if mask is defined with NaN values
!!             * specify " cf_lsm_in = 'value' if you want land regions to be defined
!!               where field 'cv_in' is strictly equal to the numeric value read into 'cv_lsm_in'
!!             * specify " cf_lsm_in = 'val+' if you want land regions to be defined
!!               where field 'cv_in' is larger or equal to the numeric value read into 'cv_lsm_in'
!!             * specify " cf_lsm_in = 'val-' if you want land regions to be defined
!!               where field 'cv_in' is smaller or equal to the numeric value read into 'cv_lsm_in'
!!               Ex: you want all points where your field is <= 0 to become land mask,
!!                   then specify: cf_lsm_in = 'val-' and cv_lsm_in = '0.00001'
!!
!! cv_lsm_in : (only relevant if ldrown==.true.)
!!             name of land-sea mask variable [char]
!!             or if cf_lsm_in = 'missing_value'--> '')
!!             by default ocean is flagged with value 1
!!             and continents are flagged with value 0
!!             Alternatively:
!!             a string of numeric value when cf_lsm_in is 'value', 'val-', or 'val+'
```

**Comment by sofiadarm** [comment]
Dear Laurent,

Thank you very much for this answer. Once again you helped a great deal!

Kind regards,
Sofia Darmaraki
