### ISSUE TITLE
NetCDF: Not a valid data type or _FillValue type mismatch

### ISSUE THREAD

**Issue by manuelbogoni** [brodeau/sosie#21]
Hello,
I need to interpolate a dataset from native ORCA1 grid (namely CESM tn1v3 grid) to ORCA025 grid (namely CESM tn0.25v3 grid).

This is the input namelist:
```
!! -------------------
!! Namelist for SOSIE
!! -------------------
!!
!! Interpolation of SST from the ORCA1 to the ORCA025 grid
!!
!!
&ndom_src
csource    = 'tn1v3'
ivect      = 0
l_reg_src  = .false.
cf_src     = 'sst_tn1v3.nc'
cv_src     = 'SST_cpl'
cv_t_src   = 'time'
cf_x_src   = 'sst_tn1v3.nc'
cv_lon_src = 'xc'
cv_lat_src = 'yc'
cf_lsm_src = 'missing_value'
cv_lsm_src = ''
ewper_src  = 0
/
!!
!!
&ndom_trg
ctarget    = 'tn025v3'
l_reg_trg  = .false.
cf_x_trg   = tn0.25v3_L50_mesh_mask.nc'
cv_lon_trg = 'nav_lon'
cv_lat_trg = 'nav_lat'
cf_lsm_trg = 'missing_value'
cv_lsm_trg = ''
ewper_trg  = 0
/
!!
!!
&ninterp
cmethod     = 'bilin'
!!
idrown      = 50, 10, .false.
ixtrpl_bot  = 0
l_save_drwn = .false.
ismooth     = 0
jt1         = 0
jt2         = 0
jplev       = 1
vmax        = 1.E6
vmin        = -1.E6
ismooth_out = 0
/
!!
!!
&noutput
cv_out    = 'SST_cpl'
cu_out    = ''
cln_out   = ''
cv_t_out  = 'time'
cd_out    = 'output'
cextra    = 'Monthly_SST_amip'
lmout     = .false.
rmiss_val = -9999.
lct       = .false.
t0        = 0.
t_stp     = 0.
cv_z_out  = ''
/
!!
```

Variable attributes from input file read:

```
float SST_cpl(time, y, x) ;
		SST_cpl:standard_name = "BCS Pseudo sea_surface_temperature" ;
		SST_cpl:long_name = "Constructed mid-month Sea Surface Temperature" ;
		SST_cpl:units = "degC" ;
		SST_cpl:coordinates = "yc xc" ;
		SST_cpl:_FillValue = 1.e+20f ;
		SST_cpl:missing_value = 1.e+20f ;
		SST_cpl:cell_methods = "time: point" ;
```

I get the following error:
```
Error occured in procedure P2D_MAPPING_AB !
Treated file     = sosie_mapping_tn1v3-tn025v3.nc
Treated variable = metrics (masking)
 --> aborting program
Netcdf message was :
NetCDF: Not a valid data type or _FillValue type mismatch
```

I am using ifort 19.0.5.281 20190815 and netCDF-cxx4 4.3.1.
Any suggestion?

**UPDATE**
Also running the provided examples _namelist.example1_bilin_ and _namelist.example3_ leads to the same issue.

**Comment by manuelbogoni** [comment]
**UPDATE**

Also running namelist.example1_bilin and namelist.example3 which are available as examples leads to the same issue.

**Comment by brodeau** [comment]
Hello,
Mhhh then I suspect something could be wrong with the version of netCDF you are using... I mean, example1 should work no matter what...
Could you try compiling SOSIE with more debugging-friendly flags such as:
-traceback -fpe0 -CB
And see if we get more information in the error message?
Cheers, /laurent

**Comment by adagj** [comment]
Hi,
I have the exact same problem. One solution seems to use an older version of the netcdf libraries
Instead of using:
module load intel/2020a netCDF-Fortran/4.5.2-iimpi-2020a netCDF/4.7.4-iimpi-2020a
I now use:
module load netCDF-Fortran/4.4.4-intel-2018b intel/2018b netCDF/4.6.1-intel-2018b
And then it worked.

Best regards, Ada

**Comment by vyacheslavkhon** [comment]
Thanks so much! 
I had the same problems with intel/20.0.4. 
Then I tried to re-compile sosie3 with different configuration: 
intel/18.0.4 ; netcdf_c-4.3.2 ; netcdf_fortran-4.4.2
and it now works!
