### ISSUE TITLE
namelist.example2 doesn't work

### ISSUE THREAD

**Issue by sunhuihang** [brodeau/sosie#26]
Hello.
I tried to interpolate 3D so data from NEMO-ORCA2 to EN.4 analiysis grid file using sosie3.x interpolation tool. I tried to imitate namelist.example2, but it always prompts that the variable cannot be found. Then i found that running namelist.example2 directly does not succeed, it will prompt Invalid argument.Could you please help me with this?

![image](https://user-images.githubusercontent.com/56792866/112949202-8abb7000-916b-11eb-8588-a73981725321.png)

Thank you in advance for your reply,
Kind regards,
Sunhh

**Comment by sunhuihang** [comment]
Please, help me. I'm dying with 3D interpolatation. There 's no 3D interpolation namelist.example can work, and have the same error. Please help!

**Comment by brodeau** [comment]
Fixed! :D
