### ISSUE TITLE
New to Fortran - build on WSL ubuntu.

### ISSUE THREAD

**Issue by securitology** [brodeau/sosie#27]
Hi completely new to Fortran and tried to build the sosie for evaluation.
On WSL ubuntu, installed gfortran, libnetcdf-dev, libnetcdff-dev.
Can you provide general instruction how to create 'make.macro' and compile ?

**Comment by brodeau** [comment]
```
>> sudo apt install gfortran-10 libnetcdf-dev libnetcdff-dev
>> ln -sf macro/make.macro_gfortran-10_Linux make.macro
>> make
```

Cheers, /laurent
