### ISSUE TITLE
Compiling fails at "USE mod_conf"

### ISSUE THREAD

**Issue by joakimkjellsson** [brodeau/sosie#33]
Good evening

I'm trying to compile SOSIE on the HLRN machine in Berlin, Germany. 
I have done the following: 
```bash
module load git
git clone -b '3.0' https://github.com/brodeau/sosie
cd sosie/

module load netcdf/intel/4.7.3 hdf5/intel/1.10.5
module load intel/18.0.6
cp macro/make.macro_intel_HLRN make.macro
export NETCDF_DIR=$(nf-config --prefix)
```

So I've got the Intel Fortran, netCDF/HDF5 and set the NETCDF_DIR variable.

The compilation works, and the lib/libsosie.a is created. But then compilation fails with
```bash
a - obj/mod_interp.o
a - obj/mod_nemotools.o
a - obj/mod_poly.o
ranlib lib/libsosie.a

ifort  src/sosie.f90 -o bin/sosie3.x -L./lib -lsosie -L/sw/dataformats/netcdf/intel.18/4.7.3/skl/lib -lnetcdf -lnetcdff ; 
src/sosie.f90(41): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MOD_CONF]
   USE mod_conf     !* important parameters, namelist, arrays, etc...
-------^
src/sosie.f90(42): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MOD_INIT]
   USE mod_init     !* important parameters, namelist, arrays, etc...
-------^
src/sosie.f90(43): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MOD_GRIDS]
   USE mod_grids    !* grided-domain module
```

(full error message is attached). 

Does anyone know what to do? As I understand it, the mod_conf should be in the libsosie.a which is clearly being linked here. 
Also tried compiling on my Macbook (using Gfortran etc) and got the same error...

Best wishes
Joakim
[sosie_compile_error.txt](https://github.com/brodeau/sosie/files/8643277/sosie_compile_error.txt)

**Comment by joakimkjellsson** [comment]
Managed to solve the issue. Turns out it was just missing the -I./mod flag for compiling. 
This works:

```bash
(py3_std) blogin8:~/sosie $ git diff
diff --git a/Makefile b/Makefile
index f2c3d74..1d5c12d 100644
--- a/Makefile
+++ b/Makefile
@@ -18,7 +18,7 @@ NCDF_INC=$(NETCDF_DIR)/include
 
 # LIBRARY linking:
 LD_NC  = -L$(NCDF_LIB) $(L_NCDF) ; # "L_NCDF" defined in make.macro ... (ex: "-lnetcdff")
-LD_ALL = -L./lib -lsosie $(LD_NC)
+LD_ALL = -I./mod -L./lib -lsosie $(LD_NC)
 
 # Disable implicit rules to speedup build
 .SUFFIXES:
@@ -105,7 +105,7 @@ bin/interp_to_hydro_section.x: src/interp_to_hydro_section.f90 $(OBJ_I2HS)
 OBJ_IJLL = obj/io_ezcdf.o obj/mod_conf.o obj/mod_manip.o
 bin/ij_from_lon_lat.x: src/ij_from_lon_lat.f90 $(OBJ_IJLL)
        @mkdir -p bin
-       $(FC) $(FF_SAFE) $(OBJ_IJLL) src/ij_from_lon_lat.f90 -o bin/ij_from_lon_lat.x $(LD_NC)
+       $(FC) $(FF_SAFE) $(OBJ_IJLL) src/ij_from_lon_lat.f90 -o bin/ij_from_lon_lat.x -I./mod $(LD_NC)
```

Cheers
Joakim

**Comment by brodeau** [comment]
Hallå där!

Mhh, the include path should not really be in the library linking section...
Better to specifies the include paths in the compilation flag specification as it is done in the template makefiles of the master:

```
# Fortran compilation flags:
# -- Common:
FF_BASE = -i4 -xHOST -I mod/ -module mod/
```

I guess it might not be the case in branch 3.0... I would use the master btw!

Cheers, /laurent

**Comment by joakimkjellsson** [comment]
Done and done! Switched to master and added the "-I /mod" to my FF_SAFE in the make.macro. No changes to makefile needed. 
Thanks!
/Joakim
