### ISSUE TITLE
Problem of compilation with gfortran

### ISSUE THREAD

**Issue by thomasarsouze** [brodeau/sosie#7]
Hi,
tried to compile trunk version of sosie on Gustafson at BSC with GCC4.9.2 & netcdf4.2
Had to modify 3 routines to make it work :
- io_ezcdf.f90 : in the READ statements, had to change '(i)' by '(i4)'
- interp_to_ground_track.f90 : in the READ statment, had to change '(f)' to '(f8.0)'. Also, had to change "xdum_r8 = SIGN(1.,180.-xlon_gt)" by "xdum_r8 = SIGN(1.,180.-REAL(xlon_gt,4))"
- mod_grids.f90 : Had to change " SIGN(1.,180.-xdum)" by " SIGN(1.,180.-REAL(xdum,4))"

Thomas

**Comment by brodeau** [comment]
Ok thanks Thomas!
Can you push your changes to the trunk?
Cheers, /laurent

**Comment by thomasarsouze** [comment]
Yes could do that. 
Just need the access do allow me the push :
"remote: Permission to brodeau/sosie.git denied to thomasarsouze."

**Comment by thomasarsouze** [comment]
Thanks for doing the appropriate update.
Thomas.

**Comment by brodeau** [comment]
Everything should complile fine with Gfortran now. Tested with Gfortran 5.
Cheers, /laurent
