### ISSUE TITLE
Mapping file from 2D to 3D

### ISSUE THREAD

**Issue by thomasarsouze** [brodeau/sosie#8]
Hi,
I've generated a 2D-mapping file from ORCA12 to ORCA025.
Both configurations got the same number of vertical levels.
Is there a tricky way to generate the 3D mapping file based on this existing 2D mapping file, without running the (costly) mapping file generation process of sosie on all levels ?
As 3D interpolation is a level-by-level interpolation, in this case I guess it's just a mater of duplicating in a smart way the existing weights...
Thanks 
Thomas.

**Comment by brodeau** [comment]
Hmm I'm not sure, the mapping is always 2D (vertical interpolation is performed 1D column-wize with 1D akima algorithm). So technically if you have the 2D mapping done for this SOURCE-TARGET setup it could be use for the 3D interpolation provided you rename the mapping file?
Was this helpful?
/laurent

**Comment by thomasarsouze** [comment]
Hi again,
So actually you're right, the same mapping file is doing the job.
Thanks for the help
Thomas.
